spring.application.name=prediction-service
server.port=8091

# Docker Network Hostnames
spring.kafka.bootstrap-servers=fvn-kafka:9092
spring.kafka.consumer.group-id=prediction-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.data.redis.host=fvn-redis
spring.data.redis.port=6379

spring.r2dbc.url=r2dbc:postgresql://fvn-postgres:5432/fogvision_db
spring.r2dbc.username=postgres
spring.r2dbc.password=password

spring.datasource.url=jdbc:postgresql://fvn-postgres:5432/fogvision_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver